-- Signal portfolio knowledge base
create extension if not exists vector with schema extensions;

create table if not exists public.knowledge_chunks (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(1536),
  created_at timestamptz not null default now()
);

create index if not exists knowledge_chunks_embedding_idx on public.knowledge_chunks using ivfflat (embedding extensions.vector_cosine_ops) with (lists = 10);

alter table public.knowledge_chunks enable row level security;
drop policy if exists "Knowledge is readable by the server only" on public.knowledge_chunks;

create or replace function public.match_knowledge(query_embedding extensions.vector(1536), match_threshold float, match_count int)
returns table (id bigint, title text, content text, metadata jsonb, similarity float)
language sql stable
as $$
  select knowledge_chunks.id, knowledge_chunks.title, knowledge_chunks.content, knowledge_chunks.metadata,
    1 - (knowledge_chunks.embedding <=> query_embedding) as similarity
  from public.knowledge_chunks
  where 1 - (knowledge_chunks.embedding <=> query_embedding) > match_threshold
  order by knowledge_chunks.embedding <=> query_embedding
  limit match_count;
$$;

-- After running this schema, seed content with scripts/seed-knowledge.mjs.
