"use client";

import { ArrowDownRight, ArrowUpRight, Check, Github, Linkedin, Mail, Menu, X } from "lucide-react";
import { useState } from "react";
import Image from "next/image";
import { aiTopics, experience, profile, resume, skills } from "@/lib/knowledge";
import { Chatbot } from "@/components/Chatbot";
import { ArchitectureDiagrams } from "@/components/ArchitectureDiagrams";

export function Portfolio() {
  const [menu, setMenu] = useState(false);
  return <main className="min-h-screen overflow-hidden bg-ink text-paper">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-10"><a href="#top" className="font-display text-lg font-bold tracking-[-.06em]">P<span className="text-acid">/</span>PRD</a><div className="hidden items-center gap-8 text-[10px] uppercase tracking-[.22em] text-mist md:flex"><a className="transition-colors hover:text-acid" href="#work">Work</a><a className="transition-colors hover:text-acid" href="#stack">Stack</a><a className="transition-colors hover:text-acid" href="#systems">Systems</a><a className="transition-colors hover:text-acid" href="#resume">Resume</a><a className="border border-white/20 px-3 py-2 text-paper hover:border-acid hover:text-acid" href="mailto:hello@pradeep.dev">Let's talk <ArrowUpRight className="ml-1 inline" size={12} /></a></div><button className="md:hidden" onClick={() => setMenu(!menu)} aria-label="Toggle navigation">{menu ? <X /> : <Menu />}</button></nav>
    {menu && <div className="border-y border-white/10 px-5 py-4 md:hidden"><div className="flex flex-col gap-4 text-xs uppercase tracking-[.2em] text-mist"><a href="#work" onClick={() => setMenu(false)}>Work</a><a href="#stack" onClick={() => setMenu(false)}>Stack</a><a href="#systems" onClick={() => setMenu(false)}>Systems</a><a href="#resume" onClick={() => setMenu(false)}>Resume</a></div></div>}
    <section id="top" className="grid-paper relative mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-20 lg:grid-cols-[1.15fr_.85fr] lg:px-10 lg:pb-32 lg:pt-28"><div className="animate-rise"><p className="mb-7 flex items-center gap-3 text-[10px] uppercase tracking-[.25em] text-acid"><span className="h-2 w-2 animate-pulse bg-acid" /> Available for select builds</p><h1 className="max-w-4xl font-display text-6xl font-medium leading-[.9] tracking-[-.075em]">I make<br /><span className="text-acid">systems</span><br />feel human.</h1><p className="mt-9 max-w-xl text-sm leading-7 text-mist">{profile.bio}</p><div className="mt-10 flex flex-wrap gap-3"><a href="#work" className="flex items-center gap-3 bg-acid px-5 py-3 text-xs font-semibold text-ink transition-transform hover:-translate-y-1">Explore the work <ArrowDownRight size={15} /></a><a href="mailto:hello@pradeep.dev" className="flex items-center gap-2 border border-white/20 px-5 py-3 text-xs text-paper hover:border-coral hover:text-coral">Start a conversation <Mail size={14} /></a></div></div><div className="animate-rise delay-2 flex flex-col justify-end border-l border-white/15 pl-6 lg:pl-12"><div className="mb-10 flex items-center gap-4"><div className="profile-frame"><Image src="/Pradeep_pic.png" alt="Portrait of Pradeep" width={82} height={82} priority className="h-20 w-20 object-cover" /></div><div><p className="font-display text-xl">{profile.name}</p><p className="mt-1 text-[9px] uppercase tracking-[.16em] text-mist">{profile.role}</p></div></div><p className="mb-12 max-w-xs font-display text-2xl leading-tight text-paper/90">“The best engineering is felt as <span className="text-coral">clarity</span>.”</p><div className="grid grid-cols-3 gap-3 border-t border-white/15 pt-5">{profile.stats.map((stat) => <div key={stat.label}><p className="font-display text-3xl tracking-[-.06em]">{stat.value}</p><p className="mt-1 text-[9px] uppercase tracking-[.15em] text-mist">{stat.label}</p></div>)}</div></div></section>
    <section className="border-y border-white/10 bg-[#101313] px-5 py-4"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 text-[10px] uppercase tracking-[.18em] text-mist"><span>Currently exploring</span><div className="flex flex-wrap gap-x-6 gap-y-2 text-paper/80"><span>↳ Evaluation-driven AI</span><span>↳ Retrieval systems</span><span>↳ Product craft</span></div></div></section>
    <section id="work" className="mx-auto max-w-7xl px-5 py-24 lg:px-10"><div className="mb-12 flex items-end justify-between border-b border-white/15 pb-5"><div><p className="mb-3 text-[10px] uppercase tracking-[.25em] text-coral">01 / Delivery capabilities</p><h2 className="font-display text-4xl tracking-[-.06em] sm:text-6xl">Systems I’ve built.</h2></div><span className="hidden text-[10px] text-mist sm:block">AWS / WEB / DATA</span></div><div className="grid gap-px bg-white/15 md:grid-cols-3">{resume.modules.map((module) => <article key={module.number} className="group relative flex min-h-[300px] flex-col justify-between bg-ink p-6 transition-colors hover:bg-[#161a18]"><div><div className="mb-12 flex items-start justify-between"><span className="grid h-10 w-10 place-items-center border border-acid text-acid">{module.number}</span><ArrowUpRight size={19} className="text-mist transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></div><h3 className="font-display text-2xl tracking-[-.05em]">{module.title}</h3><p className="mt-4 text-xs leading-6 text-mist">{module.detail}</p></div><p className="mt-8 border-t border-white/10 pt-3 text-[10px] uppercase tracking-[.12em] text-coral">Resume module / delivery</p></article>)}</div></section>
    <section id="stack" className="border-y border-white/10 bg-paper px-5 py-24 text-ink lg:px-10"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mb-3 text-[10px] uppercase tracking-[.25em] text-coral">02 / The stack</p><h2 className="font-display text-4xl leading-none tracking-[-.06em] sm:text-6xl">Tools are<br /><span className="text-coral">choices.</span></h2><p className="mt-7 max-w-sm text-xs leading-6 text-ink/60">The right tool is the one that makes the next decision clearer. Here’s the current working set.</p></div><div className="grid content-start sm:grid-cols-2">{skills.map((skill) => <div key={skill.name} className="border-b border-ink/15 py-4"><div className="flex items-center justify-between"><span className="font-display text-lg">{skill.name}</span><span className="text-[10px] text-ink/50">{skill.group}</span></div><div className="mt-3 h-1 bg-ink/10"><div className="h-1 bg-ink" style={{ width: `${skill.level}%` }} /></div></div>)}</div></div><div className="mx-auto mt-16 max-w-7xl border-t border-ink/15 pt-8"><p className="mb-5 text-[10px] uppercase tracking-[.2em] text-coral">AI implementation practice</p><div className="grid gap-px bg-ink/15 sm:grid-cols-2 lg:grid-cols-3">{aiTopics.map((topic) => <article key={topic.title} className="bg-paper p-5"><h3 className="font-display text-lg">{topic.title}</h3><p className="mt-3 text-[11px] leading-5 text-ink/60">{topic.detail}</p></article>)}</div></div></section>
    <ArchitectureDiagrams />
    <section id="about" className="mx-auto grid max-w-7xl gap-16 px-5 py-24 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><p className="mb-3 text-[10px] uppercase tracking-[.25em] text-acid">04 / The path</p><h2 className="font-display text-4xl tracking-[-.06em] sm:text-6xl">A little<br />context.</h2></div><div>{experience.map((item) => <div key={item.role} className="grid gap-3 border-t border-white/15 py-6 sm:grid-cols-[.35fr_1fr]"><p className="text-[10px] uppercase tracking-[.12em] text-coral">{item.period}</p><div><h3 className="font-display text-xl">{item.role}</h3><p className="mt-1 text-[10px] uppercase tracking-[.12em] text-mist">{item.company}</p><p className="mt-4 max-w-lg text-xs leading-6 text-mist">{item.detail}</p></div></div>)}</div></section>
    <section id="resume" className="border-y border-white/10 bg-[#151917] px-5 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><div className="mb-12 flex flex-col justify-between gap-5 border-b border-white/15 pb-6 sm:flex-row sm:items-end"><div><p className="mb-3 text-[10px] uppercase tracking-[.25em] text-coral">05 / Resume template</p><h2 className="font-display text-4xl tracking-[-.06em] sm:text-6xl">The long version.</h2></div><p className="max-w-xs text-xs leading-5 text-mist">A structured view of the experience behind the systems. Ready to turn into a PDF resume when the final contact details are added.</p></div><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="font-display text-2xl leading-tight text-acid">{resume.headline}</p><p className="mt-6 text-xs leading-6 text-mist">{resume.summary}</p><div className="mt-8 space-y-4">{resume.timeline.map((item) => <div key={item.period} className="border-l border-acid pl-4"><p className="text-[9px] uppercase tracking-[.16em] text-coral">{item.period}</p><h3 className="mt-1 font-display text-lg">{item.title}</h3><p className="mt-2 text-[11px] leading-5 text-mist">{item.detail}</p></div>)}</div></div><div><p className="mb-5 text-[10px] uppercase tracking-[.2em] text-paper/60">Selected delivery modules / Realize</p><div className="grid gap-px bg-white/15 sm:grid-cols-2">{resume.modules.map((module) => <article key={module.number} className="bg-[#151917] p-5"><span className="text-[10px] text-acid">{module.number}</span><h3 className="mt-5 font-display text-lg leading-tight">{module.title}</h3><p className="mt-3 text-[11px] leading-5 text-mist">{module.detail}</p></article>)}</div><div className="mt-10 border-t border-white/15 pt-6"><p className="mb-4 text-[10px] uppercase tracking-[.2em] text-paper/60">Technical toolkit</p><div className="grid gap-x-8 gap-y-4 sm:grid-cols-2">{Object.entries(resume.toolkit).map(([label, value]) => <div key={label}><p className="text-[9px] uppercase tracking-[.15em] text-coral">{label}</p><p className="mt-1 text-[11px] leading-5 text-mist">{value}</p></div>)}</div></div></div></div></div></section>
    <footer className="border-t border-white/10 px-5 py-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 text-[10px] uppercase tracking-[.15em] text-mist sm:flex-row"><span>© {new Date().getFullYear()} Pradeep / Built with intent</span><div className="flex gap-5"><a href="mailto:hello@pradeep.dev" className="hover:text-acid"><Mail size={14} /></a><a href="https://github.com" aria-label="GitHub" className="hover:text-acid"><Github size={14} /></a><a href="https://linkedin.com" aria-label="LinkedIn" className="hover:text-acid"><Linkedin size={14} /></a></div><span className="flex items-center gap-2 text-acid"><Check size={13} /> Open to good problems</span></div></footer>
    <Chatbot />
  </main>;
}
